version: '2'
services:
  server:
    image: lacsap/cmangos-wotlk
    #build: .
    container_name: cmangos-wotlk-server
    ports:
      - "8085:8085"
      - "3724:3724"


    links:
      - mariadb:db
    volumes:
      - /home/docker/mangos/cmangos-wotlk:/home/mangos/run/etc/
    environment:
      MYSQL_ROOT_PASSWORD: Have-Fun123


  register:
    image: lacsap/cmangos-web-register
    container_name: cmangos-wotlk-register
    ports:
      - "7080:80"

    links:
      - mariadb:db
